version: '2'
services:
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mnt/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
    redis:
        image: redis
        ports: 
            - "6379:6379"
